import type { Theme } from "../components/theme-provider";

export const defaultTheme: Theme = {
  name: "default",
  border: {
    color: "#4B5263",
    focusColor: "#61AFEF",
    style: "round",
  },
  colors: {
    accent: "#C678DD",
    accentForeground: "#282C34",
    background: "#1E1E1E",
    border: "#4B5263",
    error: "#E06C75",
    errorForeground: "#FFFFFF",
    focusRing: "#61AFEF",
    foreground: "#ABB2BF",
    info: "#56B6C2",
    infoForeground: "#FFFFFF",
    muted: "#3E4451",
    mutedForeground: "#5C6370",
    primary: "#61AFEF",
    primaryForeground: "#FFFFFF",
    secondary: "#C678DD",
    secondaryForeground: "#FFFFFF",
    selection: "#3E4451",
    selectionForeground: "#ABB2BF",
    success: "#98C379",
    successForeground: "#FFFFFF",
    warning: "#E5C07B",
    warningForeground: "#FFFFFF",
  },
  spacing: {
    0: 0,
    1: 1,
    2: 2,
    3: 3,
    4: 4,
    6: 6,
    8: 8,
  },
  typography: {
    bold: true,
    sm: "12px",
    base: "14px",
    lg: "16px",
    xl: "18px",
  },
};
