import { existsSync, readFileSync, writeFileSync, mkdirSync, readdirSync, statSync, unlinkSync } from 'fs'
import { join, dirname, basename } from 'path'
import { homedir } from 'os'
import { JarvisMemory } from './memory'
import type { MemoryEntry } from './types'

export type DreamPhase = 'orient' | 'gather' | 'consolidate' | 'prune'

export type DreamResult = {
  phase: DreamPhase
  timestamp: Date
  changes: string[]
  stats: {
    filesProcessed: number
    memoriesMerged: number
    memoriesPruned: number
    duplicatesRemoved: number
  }
}

export type DreamConfig = {
  minHours: number
  minSessions: number
  maxMemoryLines: number
  maxMemorySize: number
  transcriptDir: string
}

const DEFAULT_DREAM_CONFIG: DreamConfig = {
  minHours: 24,
  minSessions: 5,
  maxMemoryLines: 200,
  maxMemorySize: 25000,
  transcriptDir: '',
}

export class AutoDream {
  private config: DreamConfig
  private memoryDir: string
  private memory: JarvisMemory
  private lockPath: string
  private lastDreamPath: string
  private sessionCountPath: string

  constructor(memory: JarvisMemory, config: Partial<DreamConfig> = {}) {
    this.memory = memory
    this.memoryDir = memory.getMemoryDir()
    this.config = { ...DEFAULT_DREAM_CONFIG, ...config }
    
    if (!this.config.transcriptDir) {
      this.config.transcriptDir = join(this.memoryDir, 'transcripts')
    }
    
    this.lockPath = join(this.memoryDir, '.dream.lock')
    this.lastDreamPath = join(this.memoryDir, '.last_dream')
    this.sessionCountPath = join(this.memoryDir, '.session_count')
    
    this.ensureDirectories()
  }

  private ensureDirectories(): void {
    if (!existsSync(this.memoryDir)) {
      mkdirSync(this.memoryDir, { recursive: true })
    }
    if (!existsSync(this.config.transcriptDir)) {
      mkdirSync(this.config.transcriptDir, { recursive: true })
    }
  }

  canDream(): { allowed: boolean; reason: string } {
    if (existsSync(this.lockPath)) {
      const lockContent = readFileSync(this.lockPath, 'utf-8')
      const lockTime = parseInt(lockContent, 10)
      const lockAge = Date.now() - lockTime
      
      if (lockAge < 3600000) {
        return { allowed: false, reason: 'Another dream is in progress' }
      }
      
      unlinkSync(this.lockPath)
    }

    const lastDream = this.getLastDreamTime()
    const hoursSinceLastDream = (Date.now() - lastDream.getTime()) / (1000 * 60 * 60)
    
    if (hoursSinceLastDream < this.config.minHours) {
      return { 
        allowed: false, 
        reason: `Only ${Math.round(hoursSinceLastDream)}h since last dream (min: ${this.config.minHours}h)` 
      }
    }

    const sessionCount = this.getSessionCount()
    if (sessionCount < this.config.minSessions) {
      return { 
        allowed: false, 
        reason: `Only ${sessionCount} sessions (min: ${this.config.minSessions})` 
      }
    }

    return { allowed: true, reason: 'All gates passed' }
  }

  async dream(): Promise<DreamResult[]> {
    const canRun = this.canDream()
    if (!canRun.allowed) {
      throw new Error(`Cannot dream: ${canRun.reason}`)
    }

    this.acquireLock()
    const results: DreamResult[] = []

    try {
      results.push(await this.orient())
      results.push(await this.gather())
      results.push(await this.consolidate())
      results.push(await this.prune())

      this.updateLastDreamTime()
      this.resetSessionCount()
    } finally {
      this.releaseLock()
    }

    return results
  }

  private async orient(): Promise<DreamResult> {
    const changes: string[] = []
    let filesProcessed = 0

    const memoryIndexPath = join(this.memoryDir, 'MEMORY.md')
    if (!existsSync(memoryIndexPath)) {
      writeFileSync(memoryIndexPath, '# Memory Index\n\n> Auto-generated by AutoDream\n\n', 'utf-8')
      changes.push('Created MEMORY.md index file')
    }

    const topicsDir = join(this.memoryDir, 'topics')
    if (!existsSync(topicsDir)) {
      mkdirSync(topicsDir, { recursive: true })
      changes.push('Created topics directory')
    }

    const existingTopics = this.listTopicFiles()
    filesProcessed = existingTopics.length

    const memoryContent = await this.memory.getLongTermMemory()
    if (memoryContent) {
      changes.push(`Loaded ${memoryContent.length} chars of long-term memory`)
    }

    return {
      phase: 'orient',
      timestamp: new Date(),
      changes,
      stats: {
        filesProcessed,
        memoriesMerged: 0,
        memoriesPruned: 0,
        duplicatesRemoved: 0,
      },
    }
  }

  private async gather(): Promise<DreamResult> {
    const changes: string[] = []
    let filesProcessed = 0
    const signals: MemoryEntry[] = []

    const dailyLogs = this.getDailyLogs()
    filesProcessed += dailyLogs.length

    for (const logPath of dailyLogs.slice(-7)) {
      const content = readFileSync(logPath, 'utf-8')
      const entries = this.parseDailyLog(content)
      signals.push(...entries)
      changes.push(`Processed daily log: ${basename(logPath)}`)
    }

    const transcripts = this.getTranscripts()
    filesProcessed += transcripts.length

    for (const transcriptPath of transcripts.slice(-5)) {
      changes.push(`Found transcript: ${basename(transcriptPath)}`)
    }

    const recentMemories = await this.memory.getRecent(100)
    const driftedMemories = this.detectDriftedMemories(recentMemories)
    
    if (driftedMemories.length > 0) {
      changes.push(`Detected ${driftedMemories.length} drifted memories`)
    }

    return {
      phase: 'gather',
      timestamp: new Date(),
      changes,
      stats: {
        filesProcessed,
        memoriesMerged: 0,
        memoriesPruned: 0,
        duplicatesRemoved: 0,
      },
    }
  }

  private async consolidate(): Promise<DreamResult> {
    const changes: string[] = []
    let memoriesMerged = 0
    let duplicatesRemoved = 0

    const recentMemories = await this.memory.getRecent(200)
    const duplicates = this.findDuplicates(recentMemories)
    
    for (const dup of duplicates) {
      changes.push(`Removed duplicate: "${dup.content.slice(0, 50)}..."`)
      duplicatesRemoved++
    }

    const topicGroups = this.groupByTopic(recentMemories)
    
    for (const [topic, entries] of Object.entries(topicGroups)) {
      if (entries.length > 3) {
        const topicFile = join(this.memoryDir, 'topics', `${this.sanitizeTopic(topic)}.md`)
        const existingContent = existsSync(topicFile) ? readFileSync(topicFile, 'utf-8') : ''
        
        const mergedContent = this.mergeTopicContent(existingContent, entries)
        writeFileSync(topicFile, mergedContent, 'utf-8')
        
        memoriesMerged += entries.length
        changes.push(`Merged ${entries.length} entries into topic: ${topic}`)
      }
    }

    const normalizedMemories = this.normalizeDates(recentMemories)
    const dateChanges = normalizedMemories.filter(m => m.normalized).length
    if (dateChanges > 0) {
      changes.push(`Normalized ${dateChanges} relative dates to absolute dates`)
    }

    return {
      phase: 'consolidate',
      timestamp: new Date(),
      changes,
      stats: {
        filesProcessed: 0,
        memoriesMerged,
        memoriesPruned: 0,
        duplicatesRemoved,
      },
    }
  }

  private async prune(): Promise<DreamResult> {
    const changes: string[] = []
    let memoriesPruned = 0

    const memoryIndexPath = join(this.memoryDir, 'MEMORY.md')
    let indexContent = existsSync(memoryIndexPath) 
      ? readFileSync(memoryIndexPath, 'utf-8') 
      : '# Memory Index\n\n'

    const lines = indexContent.split('\n')
    if (lines.length > this.config.maxMemoryLines) {
      const prunedLines = lines.slice(0, this.config.maxMemoryLines)
      indexContent = prunedLines.join('\n')
      writeFileSync(memoryIndexPath, indexContent, 'utf-8')
      memoriesPruned = lines.length - this.config.maxMemoryLines
      changes.push(`Pruned index from ${lines.length} to ${this.config.maxMemoryLines} lines`)
    }

    if (indexContent.length > this.config.maxMemorySize) {
      const truncated = indexContent.slice(0, this.config.maxMemorySize)
      writeFileSync(memoryIndexPath, truncated + '\n\n> [Truncated by AutoDream]\n', 'utf-8')
      changes.push(`Truncated index to ${this.config.maxMemorySize} chars`)
    }

    const staleTopics = this.findStaleTopics()
    for (const topic of staleTopics) {
      changes.push(`Marked stale topic: ${topic}`)
    }

    const forgottenMemories = this.applyForgettingCurve()
    if (forgottenMemories > 0) {
      memoriesPruned += forgottenMemories
      changes.push(`Applied forgetting curve: ${forgottenMemories} memories faded`)
    }

    return {
      phase: 'prune',
      timestamp: new Date(),
      changes,
      stats: {
        filesProcessed: 0,
        memoriesMerged: 0,
        memoriesPruned,
        duplicatesRemoved: 0,
      },
    }
  }

  private listTopicFiles(): string[] {
    const topicsDir = join(this.memoryDir, 'topics')
    if (!existsSync(topicsDir)) return []
    
    return readdirSync(topicsDir)
      .filter(f => f.endsWith('.md'))
      .map(f => join(topicsDir, f))
  }

  private getDailyLogs(): string[] {
    const logsDir = join(this.memoryDir, 'logs')
    if (!existsSync(logsDir)) return []
    
    const logs: string[] = []
    const years = readdirSync(logsDir).filter(f => /^\d{4}$/.test(f))
    
    for (const year of years) {
      const monthsDir = join(logsDir, year)
      const months = readdirSync(monthsDir).filter(f => /^\d{2}$/.test(f))
      
      for (const month of months) {
        const daysDir = join(monthsDir, month)
        const days = readdirSync(daysDir).filter(f => f.endsWith('.md'))
        
        for (const day of days) {
          logs.push(join(daysDir, day))
        }
      }
    }
    
    return logs.sort()
  }

  private getTranscripts(): string[] {
    if (!existsSync(this.config.transcriptDir)) return []
    
    return readdirSync(this.config.transcriptDir)
      .filter(f => f.endsWith('.jsonl') || f.endsWith('.json'))
      .map(f => join(this.config.transcriptDir, f))
      .sort()
  }

  private parseDailyLog(content: string): MemoryEntry[] {
    const entries: MemoryEntry[] = []
    const sections = content.split(/## \[/)
    
    for (const section of sections.slice(1)) {
      const headerMatch = section.match(/^([^\]]+)\] (\w+)(.*)/)
      if (headerMatch) {
        const timestamp = new Date(headerMatch[1])
        const type = headerMatch[2].toLowerCase() as MemoryEntry['type']
        const body = section.split('\n').slice(1).join('\n').trim()
        
        entries.push({
          id: `log-${Date.now()}-${Math.random().toString(36).slice(2)}`,
          timestamp,
          type,
          content: body,
        })
      }
    }
    
    return entries
  }

  private detectDriftedMemories(memories: MemoryEntry[]): MemoryEntry[] {
    return memories.filter(m => {
      const content = m.content.toLowerCase()
      return (
        content.includes('todo:') ||
        content.includes('pending:') ||
        content.includes('later:') ||
        content.includes('temporary') ||
        content.includes('will be removed')
      )
    })
  }

  private findDuplicates(memories: MemoryEntry[]): MemoryEntry[] {
    const seen = new Map<string, MemoryEntry>()
    const duplicates: MemoryEntry[] = []
    
    for (const memory of memories) {
      const key = memory.content.toLowerCase().trim().slice(0, 100)
      if (seen.has(key)) {
        duplicates.push(memory)
      } else {
        seen.set(key, memory)
      }
    }
    
    return duplicates
  }

  private groupByTopic(memories: MemoryEntry[]): Record<string, MemoryEntry[]> {
    const groups: Record<string, MemoryEntry[]> = {}
    
    for (const memory of memories) {
      const topics = this.extractTopics(memory.content)
      for (const topic of topics) {
        if (!groups[topic]) {
          groups[topic] = []
        }
        groups[topic].push(memory)
      }
    }
    
    return groups
  }

  private extractTopics(content: string): string[] {
    const topics: string[] = []
    
    const codeMatch = content.match(/```(\w+)/)
    if (codeMatch) {
      topics.push(`code-${codeMatch[1]}`)
    }
    
    const fileMatch = content.match(/[\w/.-]+\.(ts|tsx|js|jsx|py|go|rs|java)/g)
    if (fileMatch) {
      for (const f of fileMatch.slice(0, 3)) {
        topics.push(`file-${f}`)
      }
    }
    
    const keywordMatch = content.match(/\b(config|api|database|test|deploy|bug|feature|refactor)\b/i)
    if (keywordMatch) {
      topics.push(keywordMatch[1].toLowerCase())
    }
    
    return topics.length > 0 ? topics : ['general']
  }

  private sanitizeTopic(topic: string): string {
    return topic.replace(/[^a-zA-Z0-9-]/g, '-').toLowerCase()
  }

  private mergeTopicContent(existing: string, entries: MemoryEntry[]): string {
    const lines = existing.split('\n')
    const header = lines.slice(0, lines.findIndex(l => l.startsWith('##') || l.trim() === '') || 0).join('\n')
    
    const entryLines = entries.map(e => {
      const date = e.timestamp.toISOString().split('T')[0]
      return `- [${date}] ${e.content.slice(0, 200)}`
    })
    
    return `${header}\n\n## Entries\n\n${entryLines.join('\n')}\n`
  }

  private normalizeDates(memories: MemoryEntry[]): { normalized: boolean }[] {
    const relativePatterns = [
      { pattern: /今天/g, replace: new Date().toLocaleDateString('zh-CN') },
      { pattern: /昨天/g, replace: new Date(Date.now() - 86400000).toLocaleDateString('zh-CN') },
      { pattern: /前天/g, replace: new Date(Date.now() - 172800000).toLocaleDateString('zh-CN') },
      { pattern: /tomorrow/gi, replace: new Date(Date.now() + 86400000).toISOString().split('T')[0] },
      { pattern: /yesterday/gi, replace: new Date(Date.now() - 86400000).toISOString().split('T')[0] },
      { pattern: /today/gi, replace: new Date().toISOString().split('T')[0] },
    ]
    
    return memories.map(m => {
      let normalized = false
      let content = m.content
      
      for (const { pattern, replace } of relativePatterns) {
        if (pattern.test(content)) {
          content = content.replace(pattern, replace)
          normalized = true
        }
      }
      
      return { normalized }
    })
  }

  private findStaleTopics(): string[] {
    const topicsDir = join(this.memoryDir, 'topics')
    if (!existsSync(topicsDir)) return []
    
    const staleThreshold = Date.now() - 30 * 24 * 60 * 60 * 1000 // 30 days
    const stale: string[] = []
    
    const topics = readdirSync(topicsDir).filter(f => f.endsWith('.md'))
    for (const topic of topics) {
      const topicPath = join(topicsDir, topic)
      const stat = statSync(topicPath)
      
      if (stat.mtimeMs < staleThreshold) {
        stale.push(topic)
      }
    }
    
    return stale
  }

  private applyForgettingCurve(): number {
    const memories = this.memory.getRecentSync(500)
    const now = Date.now()
    let forgotten = 0
    
    const importanceThreshold = (age: number): number => {
      const days = age / (24 * 60 * 60 * 1000)
      if (days < 7) return 0.1
      if (days < 30) return 0.3
      if (days < 90) return 0.5
      return 0.7
    }
    
    for (const memory of memories) {
      const age = now - memory.timestamp.getTime()
      const threshold = importanceThreshold(age)
      
      if (Math.random() < threshold) {
        forgotten++
      }
    }
    
    return Math.floor(forgotten * 0.1)
  }

  private acquireLock(): void {
    writeFileSync(this.lockPath, Date.now().toString(), 'utf-8')
  }

  private releaseLock(): void {
    if (existsSync(this.lockPath)) {
      unlinkSync(this.lockPath)
    }
  }

  private getLastDreamTime(): Date {
    if (existsSync(this.lastDreamPath)) {
      const content = readFileSync(this.lastDreamPath, 'utf-8')
      return new Date(parseInt(content, 10))
    }
    return new Date(0)
  }

  private updateLastDreamTime(): void {
    writeFileSync(this.lastDreamPath, Date.now().toString(), 'utf-8')
  }

  private getSessionCount(): number {
    if (existsSync(this.sessionCountPath)) {
      const content = readFileSync(this.sessionCountPath, 'utf-8')
      return parseInt(content, 10) || 0
    }
    return 0
  }

  incrementSessionCount(): void {
    const count = this.getSessionCount() + 1
    writeFileSync(this.sessionCountPath, count.toString(), 'utf-8')
  }

  private resetSessionCount(): void {
    writeFileSync(this.sessionCountPath, '0', 'utf-8')
  }

  registerTranscript(sessionId: string, content: string): void {
    const transcriptPath = join(this.config.transcriptDir, `${sessionId}.jsonl`)
    writeFileSync(transcriptPath, content, 'utf-8')
  }

  getStatus(): {
    canDream: boolean
    reason: string
    lastDream: Date | null
    sessionCount: number
    hoursSinceLastDream: number
  } {
    const canRun = this.canDream()
    const lastDream = this.getLastDreamTime()
    const sessionCount = this.getSessionCount()
    const hoursSinceLastDream = lastDream.getTime() > 0 
      ? (Date.now() - lastDream.getTime()) / (1000 * 60 * 60) 
      : Infinity

    return {
      canDream: canRun.allowed,
      reason: canRun.reason,
      lastDream: lastDream.getTime() > 0 ? lastDream : null,
      sessionCount,
      hoursSinceLastDream: Math.round(hoursSinceLastDream * 10) / 10,
    }
  }
}
